name: Image tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: 2.31.0

    - name: Start test
      shell: bash
      run: |
        cd tests
        docker compose -f docker-compose-test.yml pull --include-deps
        docker compose -f docker-compose-test.yml run --entrypoint /usr/bin/k6 k6 run --vus 2 --duration 5s /tmp/localtest.js

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        cd tests
        docker compose -f docker-compose-test.yml down